### ISSUE TITLE
Exception with Test and $instance entity

### ISSUE THREAD

**Issue by AndyCW** [microsoft/NLU.DevOps#293]
Exception in Test -s luisV3 when testing with the attached model and unit tests.

 Test Luis model2s
##[error]Process completed with exit code 134.
Run dotnet nlu test -s luisV3 -u $UNIT_TEST_FILE -o results.json
info: NLU.DevOps.CommandLine.Test.TestCommand[0]
      Running tests against NLU model...

Unhandled Exception: System.AggregateException: One or more errors occurred. (The given key '$instance' was not present in the dictionary.) ---> System.Collections.Generic.KeyNotFoundException: The given key '$instance' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NLU.DevOps.Luis.LuisNLUTestClient.GetEntities(String utterance, IDictionary`2 entities) in D:\a\1\s\src\NLU.DevOps.LuisV3\LuisNLUTestClient.cs:line 151
   at NLU.DevOps.Luis.LuisNLUTestClient.LuisResultToLabeledUtterance(SpeechPredictionResponse speechPredictionResponse) in D:\a\1\s\src\NLU.DevOps.LuisV3\LuisNLUTestClient.cs:line 205
   at NLU.DevOps.Luis.LuisNLUTestClient.TestAsync(JToken query, CancellationToken cancellationToken) in D:\a\1\s\src\NLU.DevOps.LuisV3\LuisNLUTestClient.cs:line 54
   at NLU.DevOps.CommandLine.EnumerableExtensions.<>c__DisplayClass0_0`2.<<SelectAsync>g__selectWithIndexAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NLU.DevOps.CommandLine.EnumerableExtensions.SelectAsync[T,TResult](IEnumerable`1 items, Func`2 selector, Int32 degreeOfParallelism) in D:\a\1\s\src\NLU.DevOps.CommandLine\EnumerableExtensions.cs:line 36
   at NLU.DevOps.CommandLine.Test.TestCommand.RunAsync() in D:\a\1\s\src\NLU.DevOps.CommandLine\Test\TestCommand.cs:line 51
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NLU.DevOps.CommandLine.Test.TestCommand.Main() in D:\a\1\s\src\NLU.DevOps.CommandLine\Test\TestCommand.cs:line 29
   at NLU.DevOps.CommandLine.Program.Run(ICommand command) in D:\a\1\s\src\NLU.DevOps.CommandLine\Program.cs:line 36
   at NLU.DevOps.CommandLine.Program.Main(String[] args) in D:\a\1\s\src\NLU.DevOps.CommandLine\Program.cs:line 18
##[error]Process completed with exit code 134.

[unittests.zip](https://github.com/microsoft/NLU.DevOps/files/4342994/unittests.zip)

**Comment by rozele** [comment]
Thanks @AndyCW, looking now.
